name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: '${{ matrix.os }}'
    name: "Build ${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          # - os: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda Envs
        uses: actions/cache@v2
        with:
          path: |
            ~/miniconda3
            build/*.txt
          key: ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}
          restore-keys: |
            ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}

      - name: make conda
        run:
          if [[ -e build/envs.txt ]]; then touch build/envs.txt; fi;
          if [[ -e build/deps.txt ]]; then touch build/deps.txt; fi;
          make conda

      - name: make lint
        run: make lint

      - name: make mypy
        run: make mypy

      - name: make test
        run: make test

      - name: make dist_build
        run:
          make dist_build
          mv dist/*.whl dist/pylint_ignore-ci-py2.py3-none-any.whl

      - name: upload dist
        uses: actions/upload-artifact@v2
        with:
          name: pylint_ignore-ci-py2.py3-none-any.whl
          path: dist/pylint_ignore-ci-py2.py3-none-any.whl

  build-windows:
    runs-on: windows-latest
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: pylint_ignore-ci-py2.py3-none-any.whl
